# Generated by Django 3.1.6 on 2022-06-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('dew', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('humidity', models.FloatField()),
                ('density', models.FloatField()),
                ('speed', models.FloatField()),
                ('direction', models.FloatField()),
                ('height', models.FloatField()),
                ('time', models.DateTimeField()),
                ('sensor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.sensortype')),
            ],
        ),
    ]
