# Generated by Django 3.1.6 on 2022-06-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20220614_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='sensor_name',
        ),
    ]
